### ISSUE TITLE
Template feedback: apigw-sfn

### ISSUE THREAD

**Issue by ljacobsson** [aws-samples/serverless-patterns#7]
* Inconsistent use of `Fn::GetAtt` and `!GetAtt`
* Make use of the `AWS::Serverless::StateMachine` transform and move policy from `StatesExecutionRole` to the `Policies` array:
 ```
StateMachineExpressSync:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/StateMachine.asl.json
      Policies:
         -  Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudwatch:*"
                  - "logs:*"
                Resource: "*"
     ...
```
